spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rsSystem1?characterEncoding=UTF-8
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    #  jpa:
    #    hibernate:
    #      ddl-auto: create

